### ISSUE TITLE
Commands not executing

### ISSUE THREAD

**Issue by ryanbuckner** [FlyingDiver/Indigo-Connected-Drive#24] opened 2023-06-09 14:03 UTC
I've started to receive errors (2 weeks ago)  indicating that account info request quotas have been reached so I turned the request frequency down to 15 minutes, and that seems to have fixed it. 

Commands (horn, unlock, climate, etc..) no longer work through the plugin around the same time.  However I am able to successfully send commands using the CLI for the connected package. 

```
Jun 9, 2023 at 9:56:43 AM
   Connected Drive Debug           closedPrefsConfigUi, logLevel = 5, updateFrequency = 900.0
   Connected Drive Debug           BMW 540 Account : Updating 540i xDrive (XXXXXXXXXX55588) -->  Ryan's BMW 540ix (575567701)
   Action Group                    BMW - Toggle Door Lock / Unlock
   Action Group                    BMW - Unlock
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction unlock for VIN XXXXXXXXXX55588
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction using cd_account: BMW 540 Account 
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction unlock result: None

Jun 9, 2023 at 9:58:33 AM
   Action Group                    BMW - Honk Horn
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction horn for VIN XXXXXXXXXX55588
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction using cd_account: BMW 540 Account 
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction horn result: None

```

**Comment by FlyingDiver** [comment] 2023-06-09 14:39
Hmm.  I'm not including the library, it's using the system installed version.  I need to look into this.

**Comment by ryanbuckner** [comment] 2023-06-13 14:19
These types of CLI commands are successful: 
`bimmerconnected horn emailaddress@gmail.com password north_america XXXXXXXVIN33588`

**Comment by FlyingDiver** [comment] 2023-07-12 15:25
Try upgrading the library:
```
pip3 install --upgrade bimmer_connected
```

**Comment by ryanbuckner** [comment] 2023-09-19 14:39
I've been tinkering and upgrading the library to the latest 0.14.0

I find that I'm able to run the following code to lock the car from the server and it works.  But the plugin does not do anything: 

```
import asyncio
from bimmer_connected.account import MyBMWAccount
from bimmer_connected.api.regions import Regions


account = MyBMWAccount("xxxxxx@gmail.com", "xxxxxxxx", Regions.NORTH_AMERICA)
asyncio.run(account.get_vehicles())
vehicle = account.get_vehicle("XXXXXXXXX55588")
indigo.server.log("Locking vehicle: " + vehicle.name)
result = asyncio.run(vehicle.remote_services.trigger_remote_door_lock())
indigo.server.log(result.state)
```

It takes about 70 seconds round trip: 
```
Sep 19, 2023 at 10:27:01 AM
   Embedded script executor host1 started
   Action Group                    BMW - Lock (with code)
   Script                          Locking vehicle: 540i xDrive

Sep 19, 2023 at 10:28:09 AM
   Script                          EXECUTED
```

**Comment by ryanbuckner** [comment] 2024-02-26 13:44
I just updated to your latest release, so I know the library is the latest.  Still executed actions do nothing. 

Though I can successfully update status, send CLI commands, and use the My BMW app successfully. 

```
Feb 26, 2024 at 8:37:30 AM
   Action Group                    BMW - Lock
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction lock for VIN XXXXXXXXXX55588
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction using cd_account: BMW 540 Account 
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction lock result: None

Feb 26, 2024 at 8:38:03 AM
   Connected Drive Debug           BMW 540 Account : Updating 540i xDrive (XXXXXXXXXX55588) -->  Ryan's BMW 540ix (575567701)

Feb 26, 2024 at 8:39:37 AM
   Action Group                    BMW - Lock
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction lock for VIN XXXXXXXXXX55588
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction using cd_account: BMW 540 Account 
   Connected Drive Debug           Ryan's BMW 540ix: sendCommandAction lock result: None

Feb 26, 2024 at 8:40:11 AM
   Connected Drive Debug           BMW 540 Account : Updating 540i xDrive (XXXXXXXXXX55588) -->  Ryan's BMW 540ix (575567701)
```

**Comment by FlyingDiver** [comment] 2024-02-26 14:19
I haven't had time to look into this yet.  I pushed that release because the lack of location data was causing a crash.

**Comment by ryanbuckner** [comment] 2024-02-26 18:38
No rush. Just keeping this thread updated

**Comment by FlyingDiver** [comment] 2024-11-23 18:58
Seems fixed in 2024.0.1, for some commands at least.

**Comment by FlyingDiver** [comment] 2024-11-23 19:02
https://github.com/FlyingDiver/Indigo-Connected-Drive/releases/tag/2024.0.1

**Comment by ryanbuckner** [comment] 2024-11-23 23:40
This is now working with 2024.0.3 for the first time in over a year!! Thanks Joe!!

**Comment by FlyingDiver** [comment] 2024-11-24 01:05
Please test the Send POI.  I was not able to get it to work but I'm not sure where the issue is.

**Comment by ryanbuckner** [comment] 2024-11-26 17:28
Send POI appears to be an issue with BMW or the library.  I logged an issue [here](https://github.com/bimmerconnected/bimmer_connected/issues/684)

**Comment by FlyingDiver** [comment] 2024-11-26 22:37
I subscribed to that topic so we'll see what happens.  If there's no movement in a few days I'll disable that action and push a release to the store.

**Closed** 2024-11-27 16:39 UTC
